### ISSUE TITLE
Image Preview not Working

### ISSUE THREAD

**Issue by chlebta** [jaysalvat/ezdz#10]
Hello, this is my code : 
```

$('#brandLogo').ezdz({
                text: 'drop the logo',
                preview:'http://files.parsetfss.com/12917a88-ac80-4e5e-a009-fc634161b79c/tfss-ff7efb8e-d7dc-4ace-b789-53df51de9b08-Samsung.jpg',
                validators: {
                    maxWidth: 400,
                    maxHeight: 200
                },

                reject: function(file, errors) {
                    if (errors.mimeType) {
                        alert(file.name + ' must be an image');
                    }
                    if (errors.maxWidth) {
                        alert(file.name + ' must be width:400px max');
                    }
                    if (errors.maxHeight) {
                        alert(file.name + ' must be height:200px max');
                    }
                }
            });
```
No image preview is shown in the dropzone ?

**Comment by jaysalvat** [comment]
Hello, your image file returns: 

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F6E154917DF3896B</RequestId>
<HostId>2IxCDvH5fycbbTGAX9Qsy+VrjVTPL25IFWdS0DJRNrDIBrYc0m2RSObR94PhpEQk</HostId>
<wappalyzerData id="wappalyzerData" style="display: none"/>
<script id="wappalyzerEnvDetection" src="chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/inject.js"/>
</Error>

**Comment by chlebta** [comment]
Hello, Nope it works fine : http://files.parsetfss.com/12917a88-ac80-4e5e-a009-fc634161b79c/tfss-ff7efb8e-d7dc-4ace-b789-53df51de9b08-Samsung.jpg

**Comment by Sentence** [comment]
Same issue here. (Lack of fully documentation i think. :smile:)

**Comment by jaysalvat** [comment]
Hello,

I guess it's a CORS issue. 
Picture must be on the same domain.
Is it the case?

**Comment by Sentence** [comment]
Picture on the same domain.
Cheked the source code, but need to work about the first view, so idk why i cannot get any response at console, network, etc.

**Comment by ChazyTheBest** [comment]
Same problem here, the `preview` it's not working:

    $('input[type="file"]').each(function(i) {
        $(this).ezdz({
            text: 'Arrastrar imagen',
            preview: 'http://website.com/images/' + parseInt(getUrlParameter('id')) + '/' + i + '.jpg'
        });
    });

No image is shown in the box... Only the text.

**Comment by jaysalvat** [comment]
Did you try the method?

    $('[type="file"]').ezdz('preview', 'img/previously-uploaded-logo.png');

**Comment by ChazyTheBest** [comment]
It's working that way! Thanks!

**Comment by Sentence** [comment]
Works, but cannot setup with init. Why?

```javascript
 $('input[type="file"].logo').ezdz({
        text: "Logó",
        className: "logo_dropzone",
        previewImage: true,
        preview: $(this).data("preview")
    });
    $('input[type="file"].logo').ezdz('preview', $('input[type="file"].logo').data("preview"));
```

**Comment by jaysalvat** [comment]
Hello @Sentence 

Are we talking about this:
https://github.com/jaysalvat/ezdz#value
I think it's what you need.

It can be set at init with: 

```html
 <input type="file" name="file" data-value="image.jpg" />
```

or

```javascript
$('.upload').ezdz({
    value: 'image.jpg'
});
```
