### ISSUE TITLE
IE 11 

### ISSUE THREAD

**Issue by Ajitweb** [jaysalvat/ezdz#11]
Drag and drop does not work in IE 11.
Is this a known issue - as I did not a see any mention of IE in your list of compatible browsers.
Any workaround for this?

Regards

**Comment by jaysalvat** [comment]
Hello.
As far as I know, there is no way to drag a file on an input file on IE.
You can only select a file from the file picker.

Regards.

**Comment by Ajitweb** [comment]
ok - Thanks for the answer and thank you for sharing this great utility.
