### ISSUE TITLE
multiple file inputs with image preview (preloaded from server)

### ISSUE THREAD

**Issue by ChazyTheBest** [jaysalvat/ezdz#14]
Hi, I'm wondering if it's possible to loop `preview` for each file input so I can see the currently uploaded images?

How would I do this?

Thanks!

**Comment by jaysalvat** [comment]
Hello!
I don't understand the question :p

**Comment by ChazyTheBest** [comment]
Hi and sorry.
I mean, if I have multiple file inputs it's possible to give a preview for each one without initialize ezdz multiple times?

Currently I just do this to initialize ezdz on all of my file inputs:

    $('input[type="file"]').ezdz({text: 'Arrastrar imagen'});

So it's possible to pass `preview` multiple links for each one?

**Comment by jaysalvat** [comment]
Hello,
Ezdz doesn't work with multiple file input.

**Comment by ChazyTheBest** [comment]
It does indeed... But I'll have to create classes dynamically, for the previews. Thanks anyway.

**Comment by ChazyTheBest** [comment]
#10
