### ISSUE TITLE
Multiple input files into the same page conflict

### ISSUE THREAD

**Issue by xilab** [jaysalvat/ezdz#16]
There is a conflict with 2 input fields into the same page as following.
`
<input id="moreimages" accept="image/png, image/jpeg, image/gif" type="file" name="moreimages[]" multiple >`
`<input id="moreimages" accept="image/png, image/jpeg, image/gif" type="file" name="moreimages[]" multiple >`

The first accept images and it works properly.
The second doesn't. It gives errors.

I'm initialising these 2 like this:

```
$("#moreimages").ezdz({
    	text: 'Drop images here',
        validators: {
            maxWidth:  1920,
            maxHeight: 800,
            maxNumber: 3
        },
        reject: function(file, errors) {
	        if (errors.maxWidth || errors.maxHeight) {
	            alert('The file "' + file.name + '" is too big. (1920x800 maximum)');
	        }
	        if (errors.maxNumber) {
	        	alert("You're allowed to upload 3 images maximum");
	        }
	    }
    });
    //Files
    $("#morefiles").ezdz({
    	text: 'Drop files here',
    	previewImage:  false,
        validators: {
            maxNumber: 3
        },
        reject: function(file, errors) {
	        if (errors.maxNumber) {
	        	alert("You're allowed to upload 3 files maximum");
	        }
	    }
    });
```
Is there something I can do? Thanks in advance.

**Comment by xilab** [comment]
In particulare it does not take the pdf extension.

**Comment by jaysalvat** [comment]
Hello.
In HTML, an ID must be unique. Use classes instead.
Does it work?

**Comment by jaysalvat** [comment]
It can't take the pdf extension if you only set `accept="image/png, image/jpeg, image/gif"`
You must allow PDF mime type.

**Comment by xilab** [comment]
Yes sorry It' was a typing error. My pdf input looks like this. Anyway it doesn't work. What could I do?
`
<input id="morefiles" accept="application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/pdf" type="file" name="morefiles[]" multiple >`

**Comment by xilab** [comment]
They have 2 different ids ans still don't work.

**Comment by xilab** [comment]
It only gives error with pdf. Can you try? Thanks.

**Comment by xilab** [comment]
In my console I see that the problem should be this 3 lines

```
            // No file, so user has cancelled
                if (this.files.length == 0) {
                    return;
                }
```
It seems that when a pdf is uploaded it gets like an empty file. What do you think about? Could it be?

**Comment by xilab** [comment]
Sorry for bothering you again but it seems **solved** like this in **mimeType** validation section.

`accepted = true,` instead of 'false'.

I don't know if it's correct but, since the fact all other types are blocked browser-side when you set the input 'accept' attribute, it should make the job. If you have another solutions I'd appreciate it. Thanks.

**Comment by jaysalvat** [comment]
Hello,

Just tried. ```accept="application/pdf"``` works as expected  for me.

Settings ```accepted = true``` will accept all files.

Please make a JSFiddle or something if you need me to check.

Thanks.

**Comment by xilab** [comment]
Ok, of course! I will check tomorrow and I'll send you a JSFiddle. Thanks!
