### ISSUE TITLE
Multiple uploads?

### ISSUE THREAD

**Issue by xilab** [jaysalvat/ezdz#18]
How could I allow multiple uploads with multiple previews? 
Thanks

**Comment by jaysalvat** [comment]
Hello.
Don't really understand the question. Use different ids or classes as selector.

**Comment by xilab** [comment]
I mean multiple files into the same div.

**Comment by jaysalvat** [comment]
Ezdz can only handle one upload at a time. The multiple attribute can't be used here. Sorry.

**Comment by xilab** [comment]
Ok, thank you for the explanation!
