### ISSUE TITLE
Compatibility with Microsoft EDGE

### ISSUE THREAD

**Issue by cedriccharles4** [jaysalvat/ezdz#21]
Hi :) !

Thank you for this great script :) !

My client is using EDGE and telling me the drag-and-drop is not working... Is it possible to fix that or not ?
Thank you in advance an wish you a happy new year !

**Comment by jaysalvat** [comment]
Hello @cedriccharles4 

No sorry. IE doesn't allow native drag/drop file on an input type.
Just the 'click' option works.

**Comment by cedriccharles4** [comment]
And there is no way to add (with an other script?) the drag/drop ?

**Comment by jaysalvat** [comment]
It might be possible using the Drag/Drop HTML Api.
I have no plan to add it only for IE. Sorry.
