### ISSUE TITLE
Chrome sometimes opens the file

### ISSUE THREAD

**Issue by jrhoads** [jaysalvat/ezdz#8]
Great small script for creating a dropzone.  Thank you.

I have an intermittent problem.
When I drag a file from my desktop, Chrome sometimes opens the file instead of dropping it in the zone (file input).

Any ideas?

**Comment by jaysalvat** [comment]
Hello and thanks,

No. I don't have this problem on Chrome.
So no idea.

**Comment by Titan92** [comment]
I have the same problem, but the thing is that just my client have the problem. On all my computers works fine, so i have no idea what to do.

He has W7 and Chrome, I´m using W8.1 but Chrome too.

Thanks anyway, good job!
